#!/usr/bin/env bash
set -Eeuo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MACHINE_DIR="$REPO_DIR/machine"
REFIND_BACKUP="$MACHINE_DIR/refind/refind.conf"
PKG_DIR="$MACHINE_DIR/packages"
SWAP_DIR="/swap"
SWAPFILE="/swap/swapfile"
SWAP_SIZE="20G"

info()    { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
ok()      { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
warn()    { printf '\033[1;33m! %s\033[0m\n' "$*"; }
die()     { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

usage() {
    cat <<'EOF'

Huzaifah's machine-level CachyOS recovery helper

Usage:
  ./system-setup.sh capture      Save current machine config into this repo
  ./system-setup.sh packages     Restore saved package lists
  ./system-setup.sh asus         Install ASUS ROG tools
  ./system-setup.sh hibernate    Recreate 20 GiB Btrfs hibernation swap
  ./system-setup.sh refind       Install rEFInd and restore saved config
  ./system-setup.sh refresh      Enable custom 120/240 Hz service
  ./system-setup.sh status       Show recovery-related status
  ./system-setup.sh all          Run packages + ASUS + hibernate + rEFInd + refresh

Intentionally NOT handled:
  - Secure Boot keys/signing
  - GPU/NVIDIA drivers

EOF
}

need_arch() {
    [[ -f /etc/arch-release ]] || die "This script is for Arch/CachyOS."
}

need_sudo() {
    [[ "$EUID" -ne 0 ]] || die "Run this as your normal user, not with sudo."
    sudo -v
}

confirm() {
    local prompt="$1"
    local answer
    read -r -p "$prompt [y/N]: " answer
    [[ "$answer" =~ ^([yY]|[yY][eE][sS])$ ]]
}


secure_boot_enabled() {
    local f value
    for f in /sys/firmware/efi/efivars/SecureBoot-*; do
        [[ -e "$f" ]] || continue
        value="$(od -An -t u1 -j4 -N1 "$f" 2>/dev/null | tr -d '[:space:]')"
        [[ "$value" == "1" ]] && return 0
    done
    return 1
}

find_esp() {
    local candidate
    for candidate in /boot /boot/efi /efi; do
        if mountpoint -q "$candidate" 2>/dev/null; then
            local fstype
            fstype="$(findmnt -n -o FSTYPE "$candidate" 2>/dev/null || true)"
            if [[ "$fstype" =~ ^(vfat|fat|msdos)$ ]]; then
                printf '%s\n' "$candidate"
                return 0
            fi
        fi
    done
    return 1
}

find_refind_conf() {
    local esp="$1"
    local candidate
    for candidate in \
        "$esp/EFI/refind/refind.conf" \
        "$esp/EFI/BOOT/refind.conf" \
        "$esp/refind_linux.conf"; do
        [[ -f "$candidate" ]] && { printf '%s\n' "$candidate"; return 0; }
    done

    find "$esp/EFI" -maxdepth 3 -type f -iname 'refind.conf' -print -quit 2>/dev/null || true
}

capture() {
    need_arch
    need_sudo

    info "Capturing package lists"
    mkdir -p "$PKG_DIR"

    # Keep this recovery set intentionally free of GPU-driver and Secure-Boot tooling.
    pacman -Qqen | grep -Ev \
        '^(nvidia|lib32-nvidia|opencl-nvidia|cuda|cudnn|sbctl|sbsigntools|mokutil|shim)' \
        > "$PKG_DIR/pacman.txt"

    pacman -Qqem | grep -Ev \
        '^(nvidia|lib32-nvidia|opencl-nvidia|cuda|cudnn|sbctl|sbsigntools|mokutil|shim)' \
        > "$PKG_DIR/aur.txt" || true

    ok "Saved package lists to machine/packages/"

    info "Capturing current rEFInd configuration"
    local esp
    if esp="$(find_esp)"; then
        local conf
        conf="$(find_refind_conf "$esp")"

        if [[ -n "${conf:-}" && -f "$conf" ]]; then
            mkdir -p "$(dirname "$REFIND_BACKUP")"
            sudo cp "$conf" "$REFIND_BACKUP"
            sudo chown "$USER":"$(id -gn)" "$REFIND_BACKUP"
            chmod 0644 "$REFIND_BACKUP"
            ok "Saved $conf -> machine/refind/refind.conf"
        else
            warn "No rEFInd config found on $esp"
        fi
    else
        warn "Could not identify an ESP mounted at /boot, /boot/efi or /efi"
    fi

    info "Capturing useful current-state notes"
    mkdir -p "$MACHINE_DIR"

    {
        echo "# Generated by system-setup.sh capture"
        echo "captured_at=$(date --iso-8601=seconds)"
        echo "hostname=$(hostname)"
        echo "kernel=$(uname -r)"
        echo "root_fstype=$(findmnt -n -o FSTYPE /)"
        echo "root_source=$(findmnt -n -o SOURCE /)"
        echo "root_uuid=$(findmnt -n -o UUID /)"
        echo "swap_size=$SWAP_SIZE"
    } > "$MACHINE_DIR/current-system.txt"

    ok "Capture complete."
    echo
    echo "Review before publishing:"
    echo "  git status"
    echo "  git diff -- machine/"
}

restore_packages() {
    need_arch
    need_sudo

    [[ -f "$PKG_DIR/pacman.txt" ]] || die "Run './system-setup.sh capture' first."

    info "Restoring repository packages"

    mapfile -t official < <(grep -Ev '^[[:space:]]*(#|$)' "$PKG_DIR/pacman.txt")
    if (( ${#official[@]} )); then
        # Only install packages that still exist in configured repos.
        local available=()
        local p
        for p in "${official[@]}"; do
            if pacman -Si "$p" >/dev/null 2>&1; then
                available+=("$p")
            else
                warn "Skipping unavailable repo package: $p"
            fi
        done

        if (( ${#available[@]} )); then
            sudo pacman -S --needed "${available[@]}"
        fi
    fi

    if [[ -s "$PKG_DIR/aur.txt" ]]; then
        if ! command -v paru >/dev/null 2>&1; then
            info "Installing paru"
            sudo pacman -S --needed paru
        fi

        mapfile -t foreign < <(grep -Ev '^[[:space:]]*(#|$)' "$PKG_DIR/aur.txt")
        if (( ${#foreign[@]} )); then
            info "Restoring AUR/foreign packages"
            paru -S --needed "${foreign[@]}"
        fi
    fi

    ok "Package restore complete."
    warn "GPU/NVIDIA and Secure-Boot packages were intentionally excluded."
}

setup_asus() {
    need_arch
    need_sudo

    info "Installing ASUS ROG tools"
    sudo pacman -S --needed asusctl rog-control-center power-profiles-daemon

    if systemctl is-active --quiet tlp.service 2>/dev/null || \
       systemctl is-active --quiet tuned.service 2>/dev/null; then
        warn "TLP or tuned is active. ASUS Linux recommends power-profiles-daemon instead."
        warn "Not disabling another power manager automatically."
    else
        sudo systemctl enable --now power-profiles-daemon.service
    fi

    # asusd is udev-triggered on current Arch/CachyOS packages; do not enable it manually.
    sudo udevadm trigger 2>/dev/null || true

    ok "ASUS tools installed."
    echo
    asusctl --version 2>/dev/null || true
    echo "Launch the GUI with:"
    echo "  rog-control-center"
}

setup_hibernate() {
    need_arch
    need_sudo

    local fstype
    fstype="$(findmnt -n -o FSTYPE /)"
    [[ "$fstype" == "btrfs" ]] || die "This hibernation recipe expects a Btrfs root filesystem."

    command -v btrfs >/dev/null 2>&1 || sudo pacman -S --needed btrfs-progs

    info "Configuring $SWAP_SIZE Btrfs hibernation swap"

    if swapon --show=NAME --noheadings | grep -Fxq "$SWAPFILE"; then
        ok "$SWAPFILE is already active."
    else
        if [[ ! -e "$SWAP_DIR" ]]; then
            sudo btrfs subvolume create "$SWAP_DIR"
        fi

        if [[ ! -f "$SWAPFILE" ]]; then
            sudo btrfs filesystem mkswapfile \
                --size "$SWAP_SIZE" \
                --uuid clear \
                "$SWAPFILE"
            sudo chmod 600 "$SWAPFILE"
        fi

        sudo swapon -p 10 "$SWAPFILE"
    fi

    info "Ensuring persistent fstab entry"
    local fstab_line="$SWAPFILE none swap defaults,pri=10 0 0"

    if ! grep -Eq '^[[:space:]]*/swap/swapfile[[:space:]]' /etc/fstab; then
        printf '%s\n' "$fstab_line" | sudo tee -a /etc/fstab >/dev/null
    else
        sudo sed -i \
            's|^[[:space:]]*/swap/swapfile[[:space:]].*$|/swap/swapfile none swap defaults,pri=10 0 0|' \
            /etc/fstab
    fi

    info "Setting minimum hibernation image size"
    sudo install -d /etc/tmpfiles.d
    printf '%s\n' \
        'w /sys/power/image_size - - - - 0' \
        | sudo tee /etc/tmpfiles.d/hibernation-image-size.conf >/dev/null

    echo 0 | sudo tee /sys/power/image_size >/dev/null

    info "Verifying Btrfs resume offset"
    local offset
    offset="$(sudo btrfs inspect-internal map-swapfile -r "$SWAPFILE")"
    ok "Resume offset: $offset"

    if grep -Eq '^HOOKS=.*systemd' /etc/mkinitcpio.conf 2>/dev/null; then
        ok "systemd mkinitcpio hook detected; resume support is already present."
    else
        warn "The mkinitcpio systemd hook was not detected."
        warn "Do not test hibernation until your initramfs resume mechanism is verified."
    fi

    echo
    swapon --show
    echo
    printf 'image_size: '
    cat /sys/power/image_size
    echo
    echo "The system was NOT hibernated automatically."
    echo "After reviewing the output, test manually with:"
    echo "  systemctl hibernate"
}

setup_refind() {
    need_arch
    need_sudo

    [[ -d /sys/firmware/efi ]] || die "System is not currently booted in UEFI mode."

    if secure_boot_enabled; then
        die "Secure Boot is currently enabled. Because this script intentionally does not sign EFI binaries, it will not modify rEFInd. Disable Secure Boot first or handle signing separately."
    fi

    info "Installing rEFInd package"
    sudo pacman -S --needed refind efibootmgr

    local esp
    esp="$(find_esp)" || die "Mount your EFI System Partition at /boot, /boot/efi, or /efi first."
    ok "ESP detected at $esp"

    if ! confirm "Install/reinstall rEFInd to $esp?"; then
        warn "rEFInd installation cancelled."
        return 0
    fi

    info "Running refind-install"
    sudo refind-install

    local installed_conf
    installed_conf="$(find_refind_conf "$esp")"
    [[ -n "${installed_conf:-}" ]] || die "rEFInd installed, but refind.conf could not be located."

    if [[ -f "$REFIND_BACKUP" ]]; then
        info "Restoring your saved rEFInd configuration"

        sudo cp "$installed_conf" "${installed_conf}.fresh-backup"
        sudo cp "$REFIND_BACKUP" "$installed_conf"

        # A fresh Linux install normally has a new root filesystem UUID.
        local root_uuid
        root_uuid="$(findmnt -n -o UUID /)"

        if [[ -n "$root_uuid" ]]; then
            sudo sed -Ei \
                "s#root=UUID=[0-9A-Fa-f-]+#root=UUID=$root_uuid#g" \
                "$installed_conf"
            ok "Updated root=UUID entries to the current installation: $root_uuid"
        fi

        ok "Restored $installed_conf"
    else
        warn "No saved machine/refind/refind.conf exists."
        warn "Run './system-setup.sh capture' on your current setup and commit it first."
    fi

    echo
    sudo efibootmgr || true
    echo
    warn "Secure Boot signing is intentionally NOT performed by this script."
}

enable_refresh() {
    if ! systemctl --user list-unit-files | grep -q '^auto-refresh-rate.service'; then
        die "auto-refresh-rate.service is not installed. Run ./install.sh first."
    fi

    warn "This enables Huzaifah's hardware-specific 120/240 Hz panel modeline."
    if ! confirm "Enable it on this machine?"; then
        warn "Refresh-rate service left disabled."
        return 0
    fi

    systemctl --user daemon-reload
    systemctl --user enable --now auto-refresh-rate.service
    ok "Automatic 120/240 Hz switching enabled."

    if command -v hyprctl >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
        hyprctl monitors -j 2>/dev/null \
            | jq -r '.[] | "\(.name): \(.refreshRate) Hz, scale \(.scale)"' \
            || true
    fi
}

status_report() {
    echo "================ Machine Recovery Status ================"
    echo

    printf 'OS:          '
    grep '^PRETTY_NAME=' /etc/os-release 2>/dev/null | cut -d= -f2- | tr -d '"' || true

    printf 'Kernel:      '
    uname -r

    printf 'Root FS:     '
    findmnt -n -o SOURCE,FSTYPE,UUID /

    echo
    echo "Swap:"
    swapon --show || true

    echo
    printf 'Hibernate:   '
    busctl get-property \
        org.freedesktop.login1 \
        /org/freedesktop/login1 \
        org.freedesktop.login1.Manager \
        CanHibernate 2>/dev/null || echo "unknown"

    printf 'image_size:  '
    cat /sys/power/image_size 2>/dev/null || echo "unknown"

    echo
    echo "ASUS:"
    if command -v asusctl >/dev/null 2>&1; then
        asusctl --version 2>/dev/null || true
        systemctl status asusd --no-pager -n 0 2>/dev/null | head -n 3 || true
    else
        echo "asusctl not installed"
    fi

    echo
    echo "rEFInd / EFI:"
    local esp
    if esp="$(find_esp)"; then
        echo "ESP: $esp"
        find_refind_conf "$esp" || true
    else
        echo "ESP not detected at /boot, /boot/efi or /efi"
    fi

    echo
    echo "Custom refresh service:"
    systemctl --user is-enabled auto-refresh-rate.service 2>/dev/null || true
    systemctl --user is-active auto-refresh-rate.service 2>/dev/null || true

    echo
    echo "Saved recovery files:"
    [[ -f "$REFIND_BACKUP" ]] && echo "✓ machine/refind/refind.conf" || echo "✗ machine/refind/refind.conf"
    [[ -f "$PKG_DIR/pacman.txt" ]] && echo "✓ machine/packages/pacman.txt" || echo "✗ machine/packages/pacman.txt"
    [[ -f "$PKG_DIR/aur.txt" ]] && echo "✓ machine/packages/aur.txt" || echo "✗ machine/packages/aur.txt"

    echo
    echo "Secure Boot and GPU drivers are intentionally outside this script."
}

run_all() {
    echo
    echo "This will restore MACHINE-LEVEL settings for Huzaifah's laptop:"
    echo "  • saved packages (excluding GPU/Secure Boot)"
    echo "  • ASUS ROG tools"
    echo "  • 20 GiB Btrfs hibernation swap"
    echo "  • rEFInd + saved config"
    echo "  • custom 120/240 Hz refresh service"
    echo
    echo "It will NOT configure GPU drivers or Secure Boot."
    echo

    confirm "Continue with full machine recovery?" || exit 0

    restore_packages
    setup_asus
    setup_hibernate

    if secure_boot_enabled; then
        warn "Secure Boot is enabled, so rEFInd restore is being skipped."
        warn "This script intentionally does not perform Secure Boot signing."
    else
        setup_refind
    fi

    enable_refresh

    status_report
}

main() {
    case "${1:-}" in
        capture)   capture ;;
        packages)  restore_packages ;;
        asus)      setup_asus ;;
        hibernate) setup_hibernate ;;
        refind)    setup_refind ;;
        refresh)   enable_refresh ;;
        status)    status_report ;;
        all)       run_all ;;
        -h|--help|help|"") usage ;;
        *) die "Unknown command: $1. Run ./system-setup.sh --help" ;;
    esac
}

main "$@"
