config_version = 13

[theme]
builtin = "Noctalia"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-rainbow"

[wallpaper.default]
path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

[wallpaper.last]
path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"