"Boot with standard options"  "root=UUID=__ROOT_UUID__ rw rootflags=subvol=/@ zswap.enabled=0 nowatchdog quiet splash i915.enable_dpcd_backlight=3"
"Boot to single-user mode"    "root=UUID=__ROOT_UUID__ rw rootflags=subvol=/@ zswap.enabled=0 nowatchdog quiet splash i915.enable_dpcd_backlight=3 single"
"Boot with minimal options"   "ro root=/dev/nvme0n1p5"
