-- Generated by rice-monitor-ctl.py - do not hand-edit.
--
-- Lives in conf.d, which hyprland.lua loads at the very end, so these
-- rules override the baseline monitor rules. Delete this file and reload to
-- fall back to the committed layout; `rice-monitor-ctl.py reset <output>`
-- drops a single output.

hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = 1.25 })
