pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick
import "../components/theme"
import "ThemeExportUtils.js" as ThemeExportUtils

Singleton {
    id: root

    readonly property string homeDirectory: Quickshell.env("HOME")
    readonly property string configHome: Quickshell.env("XDG_CONFIG_HOME")
        || homeDirectory + "/.config"
    readonly property string themeDirectory: configHome + "/btop/themes"
    readonly property string themePath: themeDirectory + "/desktop-profile/solstice.theme"
    property bool directoryPrepared: false
    signal preparationCompleted()

    function renderTheme(): string {
        const background = ThemeExportUtils.colorToHex(Theme.shellBackgroundColor);
        const surface = ThemeExportUtils.colorToHex(Theme.panelSurfaceColor);
        const selected = ThemeExportUtils.colorToHex(Theme.selectedSurfaceColor);
        const border = ThemeExportUtils.colorToHex(Theme.surfaceBorderColor);
        const text = ThemeExportUtils.colorToHex(Theme.primaryTextColor);
        const secondary = ThemeExportUtils.colorToHex(Theme.secondaryTextColor);
        const muted = ThemeExportUtils.colorToHex(Theme.mutedTextColor);
        const accent = ThemeExportUtils.colorToHex(Theme.accentColor);
        const accentHover = ThemeExportUtils.colorToHex(Theme.accentHoverColor);
        const success = ThemeExportUtils.colorToHex(Theme.successColor);
        const danger = ThemeExportUtils.colorToHex(Theme.dangerColor);

        return "# Generated by Quickshell. Do not edit.\n"
            + "theme[main_bg]=\"" + background + "\"\n"
            + "theme[main_fg]=\"" + text + "\"\n"
            + "theme[title]=\"" + text + "\"\n"
            + "theme[hi_fg]=\"" + accent + "\"\n"
            + "theme[selected_bg]=\"" + selected + "\"\n"
            + "theme[selected_fg]=\"" + text + "\"\n"
            + "theme[inactive_fg]=\"" + muted + "\"\n"
            + "theme[graph_text]=\"" + secondary + "\"\n"
            + "theme[proc_misc]=\"" + accentHover + "\"\n"
            + "theme[cpu_box]=\"" + accent + "\"\n"
            + "theme[mem_box]=\"" + success + "\"\n"
            + "theme[net_box]=\"" + accentHover + "\"\n"
            + "theme[proc_box]=\"" + secondary + "\"\n"
            + "theme[div_line]=\"" + border + "\"\n"
            + "theme[temp_start]=\"" + success + "\"\n"
            + "theme[temp_mid]=\"" + accentHover + "\"\n"
            + "theme[temp_end]=\"" + danger + "\"\n"
            + "theme[cpu_start]=\"" + success + "\"\n"
            + "theme[cpu_mid]=\"" + accent + "\"\n"
            + "theme[cpu_end]=\"" + danger + "\"\n"
            + "theme[free_start]=\"" + danger + "\"\n"
            + "theme[free_mid]=\"" + accent + "\"\n"
            + "theme[free_end]=\"" + success + "\"\n"
            + "theme[cached_start]=\"" + surface + "\"\n"
            + "theme[cached_mid]=\"" + accent + "\"\n"
            + "theme[cached_end]=\"" + success + "\"\n"
            + "theme[available_start]=\"" + danger + "\"\n"
            + "theme[available_mid]=\"" + accent + "\"\n"
            + "theme[available_end]=\"" + accentHover + "\"\n"
            + "theme[used_start]=\"" + success + "\"\n"
            + "theme[used_mid]=\"" + accent + "\"\n"
            + "theme[used_end]=\"" + danger + "\"\n"
            + "theme[download_start]=\"" + muted + "\"\n"
            + "theme[download_mid]=\"" + accent + "\"\n"
            + "theme[download_end]=\"" + success + "\"\n"
            + "theme[upload_start]=\"" + muted + "\"\n"
            + "theme[upload_mid]=\"" + accentHover + "\"\n"
            + "theme[upload_end]=\"" + danger + "\"\n"
            + "theme[process_start]=\"" + success + "\"\n"
            + "theme[process_mid]=\"" + accent + "\"\n"
            + "theme[process_end]=\"" + danger + "\"\n";
    }

    function prepareThemeDirectory(): void {
        if (!directoryPrepared && !directoryPreparation.running)
            directoryPreparation.running = true;
    }

    function exportTheme(): void {
        if (directoryPrepared)
            themeFile.setText(renderTheme());
    }

    FileView { id: themeFile; path: root.themePath; atomicWrites: true; printErrors: true }

    Process {
        id: directoryPreparation
        command: ["mkdir", "-p", root.themeDirectory]
        onExited: exitCode => {
            if (exitCode !== 0)
                return;
            root.directoryPrepared = true;
            root.preparationCompleted();
        }
    }
}
