pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick
import "../components/theme"
import "ThemeExportUtils.js" as ThemeExportUtils

Singleton {
    id: root

    readonly property string homeDirectory: Quickshell.env("HOME")
    readonly property string configHome: Quickshell.env("XDG_CONFIG_HOME")
        || homeDirectory + "/.config"
    readonly property string themeDirectory: configHome + "/cava/themes"
    readonly property string themePath: themeDirectory + "/desktop-profile/solstice"
    property bool directoryPrepared: false
    signal preparationCompleted()

    function renderTheme(): string {
        return "# Generated by Quickshell. Do not edit.\n"
            + "[color]\n"
            + "background = '" + ThemeExportUtils.colorToHex(Theme.shellBackgroundColor) + "'\n"
            + "foreground = '" + ThemeExportUtils.colorToHex(Theme.accentColor) + "'\n"
            + "gradient = 1\n"
            + "gradient_color_1 = '" + ThemeExportUtils.colorToHex(Theme.successColor) + "'\n"
            + "gradient_color_2 = '" + ThemeExportUtils.colorToHex(Theme.accentColor) + "'\n"
            + "gradient_color_3 = '" + ThemeExportUtils.colorToHex(Theme.accentHoverColor) + "'\n"
            + "gradient_color_4 = '" + ThemeExportUtils.colorToHex(Theme.dangerColor) + "'\n";
    }

    function prepareThemeDirectory(): void {
        if (!directoryPrepared && !directoryPreparation.running)
            directoryPreparation.running = true;
    }

    function exportTheme(): void {
        if (directoryPrepared)
            themeFile.setText(renderTheme());
    }

    FileView { id: themeFile; path: root.themePath; atomicWrites: false; printErrors: true }

    Process {
        id: directoryPreparation
        command: ["mkdir", "-p", root.themeDirectory]
        onExited: exitCode => {
            if (exitCode !== 0)
                return;
            root.directoryPrepared = true;
            root.preparationCompleted();
        }
    }
}
