pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick
import "../components/theme"

Singleton {
    id: root

    readonly property string homeDirectory: Quickshell.env("HOME")
    readonly property string configHome: Quickshell.env("XDG_CONFIG_HOME")
        || homeDirectory + "/.config"
    readonly property string dataHome: Quickshell.env("XDG_DATA_HOME")
        || homeDirectory + "/.local/share"
    readonly property string themeRoot: dataHome + "/themes"
    readonly property string iconRoot: dataHome + "/icons"
    readonly property string iconSourceRoot: Qt.resolvedUrl("../icons")
        .toString().replace(/^file:\/\//, "")
    readonly property string lightThemeName: "QuickshellDynamicLight"
    readonly property string darkThemeName: "QuickshellDynamicDark"
    readonly property string lightIconThemeName: "QuickshellSidebarLight"
    readonly property string darkIconThemeName: "QuickshellSidebarDark"
    readonly property string lightThemePath: themeRoot + "/" + lightThemeName
    readonly property string darkThemePath: themeRoot + "/" + darkThemeName
    readonly property string gtk4UserStylesheetPath: configHome + "/gtk-4.0/gtk.css"
    readonly property url templatePath: Qt.resolvedUrl("../gtk-theme.css")
    property bool directoriesPrepared: false
    property string pendingThemeName: ""
    property string pendingColorScheme: ""
    property string pendingIconThemeName: ""
    signal preparationCompleted()

    function colorToHex(colorValue: color): string {
        const channel = value => Math.round(value * 255).toString(16).padStart(2, "0");
        return "#" + channel(colorValue.r) + channel(colorValue.g)
            + channel(colorValue.b);
    }

    function mixColors(first: color, second: color, amount: real): color {
        return Qt.rgba(
            first.r + (second.r - first.r) * amount,
            first.g + (second.g - first.g) * amount,
            first.b + (second.b - first.b) * amount,
            1
        );
    }

    function toneColor(colorValue: color, lightness: real,
            minimumSaturation: real): color {
        const hue = colorValue.hslHue >= 0 ? colorValue.hslHue : 0;
        return Qt.hsla(hue, Math.max(minimumSaturation,
            Math.min(0.82, colorValue.hslSaturation)), lightness, 1);
    }

    function yellowColor(palette): color {
        return toneColor(mixColors("#f9e2af", palette.accent, 0.22),
            palette.light ? 0.42 : 0.70, 0.48);
    }

    function renderGtkStylesheet(palette): string {
        const replacements = {
            "@BACKGROUND@": colorToHex(palette.background),
            "@SURFACE@": colorToHex(palette.surface),
            "@ON_ACCENT@": colorToHex(palette.onAccent),
            "@BORDER@": colorToHex(palette.border),
            "@FOREGROUND@": colorToHex(palette.primaryText),
            "@MUTED@": colorToHex(palette.secondaryText),
            "@ACCENT@": colorToHex(palette.accent),
            "@SELECTION@": colorToHex(palette.selectedSurface),
            "@RED@": colorToHex(palette.danger),
            "@GREEN@": colorToHex(palette.success),
            "@YELLOW@": colorToHex(yellowColor(palette))
        };
        let output = templateFile.text();
        for (const token in replacements)
            output = output.split(token).join(replacements[token]);
        return "/* Generated by Quickshell. Do not edit. */\n" + output;
    }

    function renderThemeIndex(themeName: string): string {
        return "[Desktop Entry]\n"
            + "Type=X-GNOME-Metatheme\n"
            + "Name=" + themeName + "\n"
            + "Comment=Wallpaper-derived Quickshell GTK theme\n"
            + "Encoding=UTF-8\n\n"
            + "[X-GNOME-Metatheme]\n"
            + "GtkTheme=" + themeName + "\n";
    }

    function prepareThemeDirectories(): void {
        if (!directoriesPrepared && !directoryPreparation.running)
            directoryPreparation.running = true;
    }

    function exportGtkTheme(): void {
        if (!directoriesPrepared)
            return;

        lightIndexFile.setText(renderThemeIndex(lightThemeName));
        lightGtk3File.setText(renderGtkStylesheet(Theme.dynamic.lightPalette));
        lightGtk4File.setText(renderGtkStylesheet(Theme.dynamic.lightPalette));
        darkIndexFile.setText(renderThemeIndex(darkThemeName));
        darkGtk3File.setText(renderGtkStylesheet(Theme.dynamic.darkPalette));
        darkGtk4File.setText(renderGtkStylesheet(Theme.dynamic.darkPalette));

        const activeTheme = Theme.lightMode ? lightThemeName : darkThemeName;
        const inactiveTheme = Theme.lightMode ? darkThemeName : lightThemeName;
        const colorScheme = Theme.lightMode ? "prefer-light" : "prefer-dark";
        // Changing away and back makes existing GTK3 clients reload rewritten CSS.
        pendingThemeName = activeTheme;
        pendingColorScheme = colorScheme;
        pendingIconThemeName = Theme.lightMode
            ? lightIconThemeName : darkIconThemeName;
        gtkReload.command = ["dconf", "write",
            "/org/gnome/desktop/interface/gtk-theme",
            "'" + inactiveTheme + "'"];
        gtkReload.running = true;
        portalStylesheetTimer.restart();
    }

    FileView {
        id: templateFile
        path: root.templatePath
        blockLoading: true
        printErrors: true
    }

    FileView {
        id: lightIndexFile
        path: root.lightThemePath + "/index.theme"
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: lightGtk3File
        path: root.lightThemePath + "/gtk-3.0/gtk.css"
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: lightGtk4File
        path: root.lightThemePath + "/gtk-4.0/gtk.css"
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: darkIndexFile
        path: root.darkThemePath + "/index.theme"
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: darkGtk3File
        path: root.darkThemePath + "/gtk-3.0/gtk.css"
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: darkGtk4File
        path: root.darkThemePath + "/gtk-4.0/gtk.css"
        atomicWrites: true
        printErrors: false
    }

    Process {
        id: gtkReload
        onExited: {
            gtkActivate.command = ["dconf", "write",
                "/org/gnome/desktop/interface/gtk-theme",
                "'" + root.pendingThemeName + "'"];
            gtkActivate.running = true;
        }
    }

    Process {
        id: gtkActivate
        onExited: {
            iconThemeActivate.command = ["dconf", "write",
                "/org/gnome/desktop/interface/icon-theme",
                "'" + root.pendingIconThemeName + "'"];
            iconThemeActivate.running = true;
            colorSchemeActivate.command = ["dconf", "write",
                "/org/gnome/desktop/interface/color-scheme",
                "'" + root.pendingColorScheme + "'"];
            colorSchemeActivate.running = true;
        }
    }

    Process { id: iconThemeActivate }
    Process { id: colorSchemeActivate }

    Timer {
        id: portalStylesheetTimer
        interval: 800
        onTriggered: {
            const themePath = Theme.lightMode
                ? root.lightThemePath : root.darkThemePath;
            portalStylesheetLink.command = ["ln", "-sfn",
                themePath + "/gtk-4.0/gtk.css", root.gtk4UserStylesheetPath];
            portalStylesheetLink.running = true;
        }
    }

    Process {
        id: portalStylesheetLink
        onExited: exitCode => {
            if (exitCode === 0)
                portalReloadTimer.restart();
        }
    }

    Timer {
        id: portalReloadTimer
        interval: 200
        onTriggered: portalReload.running = true
    }

    Process {
        id: portalReload
        command: ["systemctl", "--user", "try-restart",
            "xdg-desktop-portal-gnome.service"]
    }

    Process {
        id: directoryPreparation
        command: ["mkdir", "-p",
            root.lightThemePath + "/gtk-3.0",
            root.lightThemePath + "/gtk-4.0",
            root.darkThemePath + "/gtk-3.0",
            root.darkThemePath + "/gtk-4.0",
            root.configHome + "/gtk-4.0",
            root.iconRoot]
        onExited: exitCode => {
            if (exitCode !== 0)
                return;
            iconThemeInstallation.running = true;
        }
    }

    Process {
        id: iconThemeInstallation
        command: ["ln", "-sfn",
            root.iconSourceRoot + "/QuickshellSidebar",
            root.iconSourceRoot + "/QuickshellSidebarLight",
            root.iconSourceRoot + "/QuickshellSidebarDark",
            root.iconRoot]
        onExited: exitCode => {
            if (exitCode !== 0)
                return;
            root.directoriesPrepared = true;
            root.preparationCompleted();
        }
    }
}
