pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick
import "../components/theme"
import "ThemeExportUtils.js" as ThemeExportUtils

Singleton {
    id: root

    readonly property string homeDirectory: Quickshell.env("HOME")
    readonly property string cacheHome: Quickshell.env("XDG_CACHE_HOME")
        || homeDirectory + "/.cache"
    readonly property string themeDirectory: cacheHome + "/desktop-profile/solstice-theme"
    readonly property string themePath: themeDirectory + "/spotify.css"
    property bool directoryPrepared: false
    signal preparationCompleted()

    function renderTheme(): string {
        return "/* Generated by Quickshell. Do not edit. */\n"
            + ":root {\n"
            + "  color-scheme: " + (Theme.lightMode ? "light" : "dark") + ";\n"
            + "  --qs-background: " + ThemeExportUtils.colorToHex(Theme.shellBackgroundColor) + ";\n"
            + "  --qs-surface: " + ThemeExportUtils.colorToHex(Theme.panelSurfaceColor) + ";\n"
            + "  --qs-surface-hover: " + ThemeExportUtils.colorToHex(Theme.hoverSurfaceColor) + ";\n"
            + "  --qs-surface-pressed: " + ThemeExportUtils.colorToHex(Theme.surfaceBorderColor) + ";\n"
            + "  --qs-surface-selected: " + ThemeExportUtils.colorToHex(Theme.selectedSurfaceColor) + ";\n"
            + "  --qs-text: " + ThemeExportUtils.colorToHex(Theme.primaryTextColor) + ";\n"
            + "  --qs-text-secondary: " + ThemeExportUtils.colorToHex(Theme.secondaryTextColor) + ";\n"
            + "  --qs-text-muted: " + ThemeExportUtils.colorToHex(Theme.mutedTextColor) + ";\n"
            + "  --qs-accent: " + ThemeExportUtils.colorToHex(Theme.accentColor) + ";\n"
            + "  --qs-accent-hover: " + ThemeExportUtils.colorToHex(Theme.accentHoverColor) + ";\n"
            + "  --qs-on-accent: " + ThemeExportUtils.colorToHex(Theme.accentTextColor) + ";\n"
            + "  --qs-positive: " + ThemeExportUtils.colorToHex(Theme.successColor) + ";\n"
            + "  --qs-negative: " + ThemeExportUtils.colorToHex(Theme.dangerColor) + ";\n"
            + "}\n";
    }

    function prepareThemeDirectory(): void {
        if (!directoryPrepared && !directoryPreparation.running)
            directoryPreparation.running = true;
    }

    function exportTheme(): void {
        if (directoryPrepared)
            themeFile.setText(renderTheme());
    }

    FileView {
        id: themeFile
        path: root.themePath
        atomicWrites: true
        printErrors: true
    }

    Process {
        id: directoryPreparation
        command: ["mkdir", "-p", root.themeDirectory]
        onExited: exitCode => {
            if (exitCode !== 0)
                return;
            root.directoryPrepared = true;
            root.preparationCompleted();
        }
    }
}
