pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick
import "../components/theme"

Singleton {
    id: root

    readonly property string homeDirectory: Quickshell.env("HOME")
    readonly property string configHome: Quickshell.env("XDG_CONFIG_HOME")
        || homeDirectory + "/.config"
    readonly property string quickshellConfigDirectory: configHome + "/desktop-profile/solstice"
    readonly property string kittyPath: quickshellConfigDirectory
        + "/terminal-colors-kitty.conf"
    readonly property string footPath: quickshellConfigDirectory
        + "/terminal-colors-foot.ini"
    property bool footUpdatePending: false

    function colorToHex(colorValue: color, includePrefix: bool): string {
        const channel = value => Math.round(value * 255).toString(16).padStart(2, "0");
        return (includePrefix ? "#" : "") + channel(colorValue.r)
            + channel(colorValue.g) + channel(colorValue.b);
    }

    function mixColors(first: color, second: color, amount: real): color {
        return Qt.rgba(
            first.r + (second.r - first.r) * amount,
            first.g + (second.g - first.g) * amount,
            first.b + (second.b - first.b) * amount,
            1
        );
    }

    function toneColor(colorValue: color, lightness: real,
            minimumSaturation: real): color {
        const hue = colorValue.hslHue >= 0 ? colorValue.hslHue : 0;
        return Qt.hsla(hue, Math.max(minimumSaturation,
            Math.min(0.82, colorValue.hslSaturation)), lightness, 1);
    }

    function harmonizeColor(semanticColor: color, amount: real): color {
        return toneColor(mixColors(semanticColor, Theme.accentColor, amount),
            Theme.lightMode ? 0.42 : 0.70, 0.48);
    }

    function terminalColors(): var {
        const yellow = harmonizeColor("#f9e2af", 0.22);
        const magenta = harmonizeColor("#f5c2e7", 0.28);
        const cyan = harmonizeColor("#94e2d5", 0.24);
        const blue = harmonizeColor("#89b4fa", 0.30);
        const regular = colorValue => toneColor(colorValue,
            Theme.lightMode ? 0.36 : 0.58, 0.44);

        return {
            background: Theme.shellBackgroundColor,
            foreground: Theme.primaryTextColor,
            selectionBackground: Theme.selectedSurfaceColor,
            selectionForeground: Theme.primaryTextColor,
            cursor: Theme.accentColor,
            url: blue,
            colors: [
                Theme.panelSurfaceColor,
                regular(Theme.dangerColor),
                regular(Theme.successColor),
                regular(yellow),
                regular(blue),
                regular(magenta),
                regular(cyan),
                Theme.secondaryTextColor,
                Theme.mutedTextColor,
                Theme.dangerColor,
                Theme.successColor,
                yellow,
                blue,
                magenta,
                cyan,
                Theme.primaryTextColor
            ]
        };
    }

    function renderKittyConfig(colors): string {
        let output = "# Generated by Quickshell. Do not edit.\n";
        output += "background " + colorToHex(colors.background, true) + "\n";
        output += "foreground " + colorToHex(colors.foreground, true) + "\n";
        output += "cursor " + colorToHex(colors.cursor, true) + "\n";
        output += "cursor_text_color " + colorToHex(Theme.accentTextColor, true) + "\n";
        output += "selection_background " + colorToHex(colors.selectionBackground, true) + "\n";
        output += "selection_foreground " + colorToHex(colors.selectionForeground, true) + "\n";
        output += "active_border_color " + colorToHex(colors.cursor, true) + "\n";
        output += "active_tab_background " + colorToHex(colors.cursor, true) + "\n";
        output += "active_tab_foreground " + colorToHex(Theme.accentTextColor, true) + "\n";
        output += "inactive_tab_background " + colorToHex(colors.colors[0], true) + "\n";
        output += "inactive_tab_foreground " + colorToHex(colors.colors[8], true) + "\n";
        output += "tab_bar_background " + colorToHex(colors.colors[0], true) + "\n";
        for (let index = 0; index < colors.colors.length; index++)
            output += "color" + index + " " + colorToHex(colors.colors[index], true) + "\n";
        return output;
    }

    function renderFootConfig(colors): string {
        let output = "# Generated by Quickshell. Do not edit.\n"
            + "[main]\n"
            + "initial-color-theme=" + (Theme.lightMode ? "light\n" : "dark\n");
        for (const section of ["dark", "light"]) {
            output += "[colors-" + section + "]\n";
            output += "alpha=0.75\n";
            output += "background=" + colorToHex(colors.background, false) + "\n";
            output += "foreground=" + colorToHex(colors.foreground, false) + "\n";
            output += "selection-background=" + colorToHex(colors.selectionBackground, false) + "\n";
            output += "selection-foreground=" + colorToHex(colors.selectionForeground, false) + "\n";
            output += "cursor=" + colorToHex(colors.background, false) + " "
                + colorToHex(colors.cursor, false) + "\n";
            output += "urls=" + colorToHex(colors.url, false) + "\n";
            for (let index = 0; index < 8; index++)
                output += "regular" + index + "=" + colorToHex(colors.colors[index], false) + "\n";
            for (let index = 0; index < 8; index++)
                output += "bright" + index + "=" + colorToHex(colors.colors[index + 8], false) + "\n";
        }
        return output;
    }

    function renderFootOsc(colors): string {
        const osc = (code, value) => "\u001b]" + code + ";" + value + "\u0007";
        let output = osc("10", "#" + colorToHex(colors.foreground, false));
        output += osc("11", "#" + colorToHex(colors.background, false));
        output += osc("12", "#" + colorToHex(colors.cursor, false));
        output += osc("17", "#" + colorToHex(colors.selectionBackground, false));
        output += osc("19", "#" + colorToHex(colors.selectionForeground, false));
        for (let index = 0; index < colors.colors.length; index++)
            output += osc("4", index + ";#" + colorToHex(colors.colors[index], false));
        return output;
    }

    function exportTerminalTheme(): void {
        const colors = terminalColors();
        kittyFile.setText(renderKittyConfig(colors));
        footFile.setText(renderFootConfig(colors));
    }

    function updateLiveFootTheme(): void {
        if (footLiveUpdate.running) {
            footUpdatePending = true;
            return;
        }

        const colors = terminalColors();
        const signal = Theme.lightMode ? "-USR2" : "-USR1";
        const script = "pkill " + signal + " -x foot 2>/dev/null || true; "
            + "sleep 0.05; seen=' '; "
            + "for environment in /proc/[0-9]*/environ; do "
            + "if tr '\\0' '\\n' < \"$environment\" 2>/dev/null | grep -qx 'TERM=foot'; then "
            + "process=${environment%/environ}; tty=$(readlink \"$process/fd/1\" 2>/dev/null); "
            + "case \"$tty\" in /dev/pts/[0-9]*) "
            + "case \"$seen\" in *\" $tty \"*) ;; *) "
            + "seen=\"$seen$tty \"; printf '%s' \"$1\" > \"$tty\" 2>/dev/null || true ;; esac ;; esac; fi; done";
        footLiveUpdate.command = ["sh", "-c", script, "sh", renderFootOsc(colors)];
        footLiveUpdate.running = true;
    }

    function reloadKittyTheme(): void {
        kittyReload.command = ["sh", "-c",
            "for pid in $(pgrep -f '^kitty( |$)'); do kitty @ --to unix:@quickshell-kitty-$pid set-colors --all --configured \"$1\"; done",
            "sh", kittyPath];
        kittyReload.running = true;
    }

    FileView {
        id: kittyFile
        path: root.kittyPath
        atomicWrites: true
        printErrors: true
        onSaved: root.reloadKittyTheme()
    }

    FileView {
        id: footFile
        path: root.footPath
        atomicWrites: true
        printErrors: true
        onSaved: root.updateLiveFootTheme()
    }

    Process { id: kittyReload }
    Process {
        id: footLiveUpdate
        onExited: {
            if (root.footUpdatePending) {
                root.footUpdatePending = false;
                root.updateLiveFootTheme();
            }
        }
    }
}
