pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick
import "../components/theme"
import "ThemeExportUtils.js" as ThemeExportUtils

Singleton {
    id: root

    readonly property string homeDirectory: Quickshell.env("HOME")
    readonly property string configHome: Quickshell.env("XDG_CONFIG_HOME")
        || homeDirectory + "/.config"
    readonly property string themePath: configHome + "/desktop-profile/solstice/tmux-colors.conf"

    function renderTheme(): string {
        const surface = ThemeExportUtils.colorToHex(Theme.panelSurfaceColor);
        const hover = ThemeExportUtils.colorToHex(Theme.hoverSurfaceColor);
        const border = ThemeExportUtils.colorToHex(Theme.surfaceBorderColor);
        const selected = ThemeExportUtils.colorToHex(Theme.selectedSurfaceColor);
        const text = ThemeExportUtils.colorToHex(Theme.primaryTextColor);
        const secondary = ThemeExportUtils.colorToHex(Theme.secondaryTextColor);
        const muted = ThemeExportUtils.colorToHex(Theme.mutedTextColor);
        const accent = ThemeExportUtils.colorToHex(Theme.accentColor);
        const accentText = ThemeExportUtils.colorToHex(Theme.accentTextColor);
        const danger = ThemeExportUtils.colorToHex(Theme.dangerColor);

        return "# Generated by Quickshell. Do not edit.\n"
            + "set -g status-style \"bg=" + surface + ",fg=" + text + "\"\n"
            + "set -g status-left-style \"bg=" + accent + ",fg=" + accentText + ",bold\"\n"
            + "set -g status-right-style \"bg=" + surface + ",fg=" + secondary + "\"\n"
            + "set -g window-status-style \"bg=" + surface + ",fg=" + muted + "\"\n"
            + "set -g window-status-current-style \"bg=" + selected + ",fg=" + text + ",bold\"\n"
            + "set -g window-status-activity-style \"bg=" + hover + ",fg=" + accent + ",bold\"\n"
            + "set -g window-status-bell-style \"bg=" + danger + ",fg=" + accentText + ",bold\"\n"
            + "set -g message-style \"bg=" + selected + ",fg=" + text + "\"\n"
            + "set -g message-command-style \"bg=" + selected + ",fg=" + accent + "\"\n"
            + "set -g mode-style \"bg=" + accent + ",fg=" + accentText + ",bold\"\n"
            + "set -g pane-border-style \"fg=" + border + "\"\n"
            + "set -g pane-active-border-style \"fg=" + accent + "\"\n"
            + "set -g clock-mode-colour \"" + accent + "\"\n"
            + "set -g display-panes-colour \"" + muted + "\"\n"
            + "set -g display-panes-active-colour \"" + accent + "\"\n";
    }

    function exportTheme(): void {
        themeFile.setText(renderTheme());
    }

    FileView {
        id: themeFile
        path: root.themePath
        atomicWrites: true
        printErrors: true
        onSaved: tmuxReload.running = true
    }

    Process {
        id: tmuxReload
        command: ["tmux", "source-file", root.themePath]
    }
}
