-- Noctalia v5 Multi-Rice profile
-- Native Noctalia shell; NOT a Quickshell provider.

hl.config({ autogenerated = false })

-- Portable GPU handling:
-- use the ASUS G16 iGPU node when present, otherwise allow auto-detection.
local aq_drm_device = "/dev/dri/intel-igpu"
local aq_drm_exists = os.execute("test -e " .. aq_drm_device)

if aq_drm_exists == true or aq_drm_exists == 0 then
    hl.env("AQ_DRM_DEVICES", aq_drm_device)
end

local home = os.getenv("HOME")
local hypr = home .. "/.config/hypr"

package.path =
    package.path ..
    ";" .. hypr .. "/?.lua" ..
    ";" .. hypr .. "/?/init.lua"

require("config.variables")
require("config.environment")
require("config.monitors")
require("config.inputs")
require("config.misc")
require("config.colors")
require("config.animations")
require("config.decorations")
require("config.workspaces")
require("config.windowrules")

require("config.autostart")
require("config.binds")
